import "./media/favicon-32.png";
// import "./media/favicon-64.png";
import "./media/favicon-76.png";
import "./media/favicon-120.png";
// import "./media/favicon-128.png";
import "./media/favicon-144.png";
import "./media/favicon-152.png";
// import "./media/favicon-167.png";
import "./media/favicon-180.png";
import "./media/favicon-192.png";
// import "./media/favicon-196.png";
// import "./media/favicon-228.png";
import "./media/browserconfig.xml";
